#!/bin/sh

#SBATCH -A DBS21007
#SBATCH --job-name=ds003709-mriqc
#SBATCH --mail-type=END
#SBATCH --mail-user=jbwexler@tutanota.com
#SBATCH --output=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/mriqc/ds003709-mriqc/.reproman/jobs/local/20220304-050932-ff86/stdout
#SBATCH --error=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/mriqc/ds003709-mriqc/.reproman/jobs/local/20220304-050932-ff86/stderr

#SBATCH --nodes=11
#SBATCH --ntasks=51
#SBATCH --time=8:00:00
#SBATCH --partition=normal

metadir=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/mriqc/ds003709-mriqc/.reproman/jobs/local/20220304-050932-ff86

module load launcher
module load remora
export LAUNCHER_JOB_FILE="$metadir/launcher"

for task_id in $(seq 0 50); do
    printf "$metadir/runscript %d >$metadir/stdout.%d 2>$metadir/stderr.%d\n" \
      "$task_id" "$task_id" "$task_id" >>"$LAUNCHER_JOB_FILE"
done

remora "$LAUNCHER_DIR"/paramrun